
package com.soa.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoWebServerImplService", targetNamespace = "http://service.soa.com/", wsdlLocation = "http://localhost:8000/demoservice?wsdl")
public class DemoWebServerImplService
    extends Service
{

    private final static URL DEMOWEBSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOWEBSERVERIMPLSERVICE_EXCEPTION;
    private final static QName DEMOWEBSERVERIMPLSERVICE_QNAME = new QName("http://service.soa.com/", "DemoWebServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/demoservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOWEBSERVERIMPLSERVICE_WSDL_LOCATION = url;
        DEMOWEBSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public DemoWebServerImplService() {
        super(__getWsdlLocation(), DEMOWEBSERVERIMPLSERVICE_QNAME);
    }

    public DemoWebServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOWEBSERVERIMPLSERVICE_QNAME, features);
    }

    public DemoWebServerImplService(URL wsdlLocation) {
        super(wsdlLocation, DEMOWEBSERVERIMPLSERVICE_QNAME);
    }

    public DemoWebServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOWEBSERVERIMPLSERVICE_QNAME, features);
    }

    public DemoWebServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoWebServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoWebServer
     */
    @WebEndpoint(name = "DemoWebServerImplPort")
    public DemoWebServer getDemoWebServerImplPort() {
        return super.getPort(new QName("http://service.soa.com/", "DemoWebServerImplPort"), DemoWebServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoWebServer
     */
    @WebEndpoint(name = "DemoWebServerImplPort")
    public DemoWebServer getDemoWebServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soa.com/", "DemoWebServerImplPort"), DemoWebServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOWEBSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw DEMOWEBSERVERIMPLSERVICE_EXCEPTION;
        }
        return DEMOWEBSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
